export interface ServerDataItem {
    id: string;
    name: string;
    email: string;
}

export const SERVER_DATA: ServerDataItem[] = [
    { id: "1", name: "Alice Johnson", email: "alice.johnson@example.com" },
    { id: "2", name: "Bob Smith", email: "bob.smith@example.com" },
    { id: "3", name: "Carol Williams", email: "carol.williams@example.com" },
    { id: "4", name: "David Brown", email: "david.brown@example.com" },
    { id: "5", name: "Eva Davis", email: "eva.davis@example.com" },
    { id: "6", name: "Frank Miller", email: "frank.miller@example.com" },
    { id: "7", name: "Grace Wilson", email: "grace.wilson@example.com" },
    { id: "8", name: "Henry Moore", email: "henry.moore@example.com" },
    { id: "9", name: "Ivy Taylor", email: "ivy.taylor@example.com" },
    { id: "10", name: "Jack Anderson", email: "jack.anderson@example.com" },
    { id: "11", name: "Kate Thomas", email: "kate.thomas@example.com" },
    { id: "12", name: "Leo Jackson", email: "leo.jackson@example.com" },
    { id: "13", name: "Mia White", email: "mia.white@example.com" },
    { id: "14", name: "Noah Harris", email: "noah.harris@example.com" },
    { id: "15", name: "Olivia Martin", email: "olivia.martin@example.com" },
    { id: "16", name: "Paul Thompson", email: "paul.thompson@example.com" },
    { id: "17", name: "Quinn Garcia", email: "quinn.garcia@example.com" },
    { id: "18", name: "Rachel Martinez", email: "rachel.martinez@example.com" },
    { id: "19", name: "Sam Robinson", email: "sam.robinson@example.com" },
    { id: "20", name: "Tina Clark", email: "tina.clark@example.com" },
    { id: "21", name: "Uma Rodriguez", email: "uma.rodriguez@example.com" },
    { id: "22", name: "Victor Lewis", email: "victor.lewis@example.com" },
    { id: "23", name: "Wendy Lee", email: "wendy.lee@example.com" },
    { id: "24", name: "Xavier Walker", email: "xavier.walker@example.com" },
    { id: "25", name: "Yara Hall", email: "yara.hall@example.com" },
    { id: "26", name: "Zach Allen", email: "zach.allen@example.com" },
    { id: "27", name: "Amy Young", email: "amy.young@example.com" },
    { id: "28", name: "Ben King", email: "ben.king@example.com" },
    { id: "29", name: "Chloe Wright", email: "chloe.wright@example.com" },
    { id: "30", name: "Derek Scott", email: "derek.scott@example.com" },
    { id: "31", name: "Emma Green", email: "emma.green@example.com" },
    { id: "32", name: "Felix Adams", email: "felix.adams@example.com" },
    { id: "33", name: "Gina Baker", email: "gina.baker@example.com" },
    { id: "34", name: "Hugo Nelson", email: "hugo.nelson@example.com" },
    { id: "35", name: "Isla Hill", email: "isla.hill@example.com" },
    { id: "36", name: "Jake Flores", email: "jake.flores@example.com" },
    { id: "37", name: "Kara Mitchell", email: "kara.mitchell@example.com" },
    { id: "38", name: "Liam Roberts", email: "liam.roberts@example.com" },
    { id: "39", name: "Maya Turner", email: "maya.turner@example.com" },
    { id: "40", name: "Nate Phillips", email: "nate.phillips@example.com" },
    { id: "41", name: "Oscar Campbell", email: "oscar.campbell@example.com" },
    { id: "42", name: "Piper Parker", email: "piper.parker@example.com" },
    { id: "43", name: "Quinn Evans", email: "quinn.evans@example.com" },
    { id: "44", name: "Riley Edwards", email: "riley.edwards@example.com" },
    { id: "45", name: "Sofia Collins", email: "sofia.collins@example.com" },
    { id: "46", name: "Theo Stewart", email: "theo.stewart@example.com" },
    { id: "47", name: "Uma Sanchez", email: "uma.sanchez@example.com" },
    { id: "48", name: "Vera Morris", email: "vera.morris@example.com" },
    { id: "49", name: "Will Rogers", email: "will.rogers@example.com" },
    { id: "50", name: "Xena Reed", email: "xena.reed@example.com" },
    { id: "51", name: "Yuki Cook", email: "yuki.cook@example.com" },
    { id: "52", name: "Zara Morgan", email: "zara.morgan@example.com" },
];
