import type { Metadata } from "next";
import { DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";

const DMSans = DM_Sans({
    subsets: ["latin"],
    variable: "--font-sans",
});

const DMMono = DM_Mono({
    subsets: ["latin"],
    variable: "--font-mono",
    weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${DMSans.variable} ${DMMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
